INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',2,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-13',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',3,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-27',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',4,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-09',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',5,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-17',2,'Il prodotto costa troppo.',6,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-28',2,'Il prodotto costa troppo.',7,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',8,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-13',1,'Il prodotto non funziona.',9,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-21',2,'Il prodotto costa troppo.',10,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-09',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',12,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-14',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',13,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-07',2,'Il prodotto costa troppo.',14,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-16',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',15,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-06',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',16,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-01',1,'Il prodotto non funziona.',17,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-10',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',18,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-28',2,'Il prodotto costa troppo.',19,1);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-09',2,'Il prodotto costa troppo.',20,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-08',1,'Il prodotto non funziona.',21,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-28',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',22,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',23,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-17',1,'Il prodotto non funziona.',24,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-10',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',25,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-22',1,'Il prodotto non funziona.',26,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-28',2,'Il prodotto costa troppo.',27,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-12',2,'Il prodotto costa troppo.',28,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-04',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',29,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',30,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-23',1,'Il prodotto non funziona.',31,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-24',2,'Il prodotto costa troppo.',32,2);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',33,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-24',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',34,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-19',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',35,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-30',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',36,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',37,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-24',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',38,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-05',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',39,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-06',1,'Il prodotto non funziona.',40,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-21',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',41,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-11',1,'Il prodotto non funziona.',42,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-20',2,'Il prodotto costa troppo.',43,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-16',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',44,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-05',2,'Il prodotto costa troppo.',45,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-30',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',46,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-18',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',47,3);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-26',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',48,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-09',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',2,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-29',2,'Il prodotto costa troppo.',3,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-01',2,'Il prodotto costa troppo.',4,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-25',2,'Il prodotto costa troppo.',5,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-19',2,'Il prodotto costa troppo.',6,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-01',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',7,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-09',2,'Il prodotto costa troppo.',8,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-03',1,'Il prodotto non funziona.',9,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-06',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',10,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-30',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',11,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',12,4);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-21',1,'Il prodotto non funziona.',13,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-23',1,'Il prodotto non funziona.',14,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-11',2,'Il prodotto costa troppo.',15,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-11',1,'Il prodotto non funziona.',16,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-28',1,'Il prodotto non funziona.',17,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-15',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',18,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-12',1,'Il prodotto non funziona.',19,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-16',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',20,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-28',1,'Il prodotto non funziona.',21,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-15',2,'Il prodotto costa troppo.',22,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-18',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',23,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',24,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',25,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-01',2,'Il prodotto costa troppo.',26,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-10',1,'Il prodotto non funziona.',27,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-06',2,'Il prodotto costa troppo.',28,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-10',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',29,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-05',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',30,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-30',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',31,5);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-16',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',32,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-05',2,'Il prodotto costa troppo.',33,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-28',2,'Il prodotto costa troppo.',34,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-17',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',35,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',36,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-01',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',37,6);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',38,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-22',2,'Il prodotto costa troppo.',39,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-26',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',40,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-24',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',41,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-02',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',42,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',43,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-22',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',44,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',45,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-03',2,'Il prodotto costa troppo.',46,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',47,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-14',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',48,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-31',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',2,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-12',2,'Il prodotto costa troppo.',3,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-07',1,'Il prodotto non funziona.',4,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-07',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',5,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-01',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',6,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-12',1,'Il prodotto non funziona.',7,8);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',8,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-30',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',9,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-18',2,'Il prodotto costa troppo.',10,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-07',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',12,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-29',1,'Il prodotto non funziona.',13,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-17',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',14,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-18',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',15,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-08',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',16,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-31',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',17,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',18,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-01',2,'Il prodotto costa troppo.',19,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-23',2,'Il prodotto costa troppo.',20,42);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-17',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',21,221);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-21',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',22,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-24',2,'Il prodotto costa troppo.',23,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-08',2,'Il prodotto costa troppo.',24,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-04',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',25,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-05',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',26,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-05',2,'Il prodotto costa troppo.',27,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-22',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',28,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-25',1,'Il prodotto non funziona.',29,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-19',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',30,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-04',2,'Il prodotto costa troppo.',31,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-05',2,'Il prodotto costa troppo.',32,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',33,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-03',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',34,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-19',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',35,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-09',2,'Il prodotto costa troppo.',36,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',37,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-21',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',38,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-24',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',39,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-27',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',40,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-14',1,'Il prodotto non funziona.',41,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-07',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',42,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-17',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',43,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-10',1,'Il prodotto non funziona.',44,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-29',2,'Il prodotto costa troppo.',45,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-02',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',46,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-13',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',47,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-16',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',48,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-08',1,'Il prodotto non funziona.',2,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',3,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-27',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',4,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-31',1,'Il prodotto non funziona.',5,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-06',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',6,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-18',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',7,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-03',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',8,211);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-29',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',9,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-03',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',10,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',12,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-17',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',13,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-04',1,'Il prodotto non funziona.',14,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-11',1,'Il prodotto non funziona.',15,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-08',2,'Il prodotto costa troppo.',16,214);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-07',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',17,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-22',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',18,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-16',2,'Il prodotto costa troppo.',19,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-24',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',20,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-25',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',21,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-03',2,'Il prodotto costa troppo.',22,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-17',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',23,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-27',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',24,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',25,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-05',1,'Il prodotto non funziona.',26,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-10',1,'Il prodotto non funziona.',27,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-31',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',28,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-09',1,'Il prodotto non funziona.',29,217);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-25',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',30,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',31,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-05',1,'Il prodotto non funziona.',32,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-22',1,'Il prodotto non funziona.',33,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-27',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',34,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-28',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',35,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-29',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',36,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-25',1,'Il prodotto non funziona.',37,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-06',1,'Il prodotto non funziona.',38,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-17',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',39,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-22',2,'Il prodotto costa troppo.',40,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-15',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',41,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-17',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',42,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-03',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',43,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-27',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',44,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-08',1,'Il prodotto non funziona.',45,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-26',2,'Il prodotto costa troppo.',46,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-03',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',47,146);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-10',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',48,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-29',2,'Il prodotto costa troppo.',2,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-18',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',3,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-26',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',4,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-24',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',5,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-20',1,'Il prodotto non funziona.',6,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-27',2,'Il prodotto costa troppo.',7,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-26',2,'Il prodotto costa troppo.',8,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',9,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-10',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',10,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-02',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-02',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',12,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-10',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',13,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-14',1,'Il prodotto non funziona.',14,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-19',1,'Il prodotto non funziona.',15,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-04',1,'Il prodotto non funziona.',16,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-08',1,'Il prodotto non funziona.',17,147);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-31',1,'Il prodotto non funziona.',18,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-06',2,'Il prodotto costa troppo.',19,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-31',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',20,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-14',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',21,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-21',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',22,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-27',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',23,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-23',1,'Il prodotto non funziona.',24,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-28',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',25,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-03',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',26,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-02',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',27,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-02',1,'Il prodotto non funziona.',28,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-01',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',29,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',30,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-05',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',31,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',32,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-06',1,'Il prodotto non funziona.',33,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-03',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',34,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-30',1,'Il prodotto non funziona.',35,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-06',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',36,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-29',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',37,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-17',1,'Il prodotto non funziona.',38,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-30',1,'Il prodotto non funziona.',39,148);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-19',2,'Il prodotto costa troppo.',40,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-30',2,'Il prodotto costa troppo.',41,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-04',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',42,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-12',2,'Il prodotto costa troppo.',43,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-11',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',44,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-25',2,'Il prodotto costa troppo.',45,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-02',2,'Il prodotto costa troppo.',46,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',47,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',48,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-08',2,'Il prodotto costa troppo.',2,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-27',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',3,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-14',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',4,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',5,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-06',1,'Il prodotto non funziona.',6,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-16',1,'Il prodotto non funziona.',7,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-19',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',8,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-20',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',9,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-21',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',10,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-18',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',11,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-24',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',12,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-11',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',13,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-09',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',14,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-23',2,'Il prodotto costa troppo.',15,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-05',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',16,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-10',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',17,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-04',1,'Il prodotto non funziona.',18,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',19,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',20,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-13',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',21,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-09',1,'Il prodotto non funziona.',22,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-04',2,'Il prodotto costa troppo.',23,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-06',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',24,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-25',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',25,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-25',2,'Il prodotto costa troppo.',26,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-29',1,'Il prodotto non funziona.',27,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-06',1,'Il prodotto non funziona.',28,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',29,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-10',1,'Il prodotto non funziona.',30,149);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-12',2,'Il prodotto costa troppo.',31,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',32,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-24',1,'Il prodotto non funziona.',33,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-07',1,'Il prodotto non funziona.',34,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-30',2,'Il prodotto costa troppo.',35,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-23',2,'Il prodotto costa troppo.',36,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-29',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',37,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-11',1,'Il prodotto non funziona.',38,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-08',1,'Il prodotto non funziona.',39,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-08',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',40,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',41,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-28',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',42,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',43,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-17',2,'Il prodotto costa troppo.',44,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-15',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',45,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-27',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',46,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-24',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',47,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-05',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',48,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-08',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',2,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-27',1,'Il prodotto non funziona.',3,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',4,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',5,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-23',1,'Il prodotto non funziona.',6,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-08',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',7,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-18',1,'Il prodotto non funziona.',8,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-27',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',9,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-07',2,'Il prodotto costa troppo.',10,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-07',1,'Il prodotto non funziona.',11,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-18',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',12,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-03',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',13,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',14,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-21',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',15,150);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-02',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',16,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-14',2,'Il prodotto costa troppo.',17,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-12',1,'Il prodotto non funziona.',18,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-15',1,'Il prodotto non funziona.',19,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-05',1,'Il prodotto non funziona.',20,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-21',2,'Il prodotto costa troppo.',21,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-15',2,'Il prodotto costa troppo.',22,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-04',2,'Il prodotto costa troppo.',23,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-21',2,'Il prodotto costa troppo.',24,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-19',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',25,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-13',2,'Il prodotto costa troppo.',26,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-09',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',27,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-30',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',28,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',29,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-24',2,'Il prodotto costa troppo.',30,151);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-28',1,'Il prodotto non funziona.',31,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-28',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',32,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-21',2,'Il prodotto costa troppo.',33,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-07',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',34,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-12',2,'Il prodotto costa troppo.',35,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-05',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',36,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-27',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',37,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-01',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',38,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-10',2,'Il prodotto costa troppo.',39,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-08',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',40,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-13',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',41,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-02',1,'Il prodotto non funziona.',42,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-28',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',43,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',44,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',45,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-06',2,'Il prodotto costa troppo.',46,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-07',1,'Il prodotto non funziona.',47,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-03',1,'Il prodotto non funziona.',48,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-13',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',2,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',3,152);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-03',1,'Il prodotto non funziona.',4,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-15',2,'Il prodotto costa troppo.',5,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-04',2,'Il prodotto costa troppo.',6,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-06',2,'Il prodotto costa troppo.',7,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',8,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',9,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-28',1,'Il prodotto non funziona.',10,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-01',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',11,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',12,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-03',1,'Il prodotto non funziona.',13,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-28',1,'Il prodotto non funziona.',14,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-16',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',15,153);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-14',2,'Il prodotto costa troppo.',16,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',17,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-08',1,'Il prodotto non funziona.',18,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',19,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',20,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-23',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',21,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-16',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',22,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-01',1,'Il prodotto non funziona.',23,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-19',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',24,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',25,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-23',2,'Il prodotto costa troppo.',26,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-07',2,'Il prodotto costa troppo.',27,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-12',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',28,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-13',1,'Il prodotto non funziona.',29,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-04',1,'Il prodotto non funziona.',30,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',31,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-13',2,'Il prodotto costa troppo.',32,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-11',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',33,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-13',2,'Il prodotto costa troppo.',34,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-09',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',35,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-06',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',36,154);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-11',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',37,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-09',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',38,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-09',2,'Il prodotto costa troppo.',39,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-09',1,'Il prodotto non funziona.',40,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-25',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',41,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-01',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',42,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-29',2,'Il prodotto costa troppo.',43,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-27',1,'Il prodotto non funziona.',44,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-31',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',45,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-30',1,'Il prodotto non funziona.',46,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-28',1,'Il prodotto non funziona.',47,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',48,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-06',1,'Il prodotto non funziona.',2,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-22',2,'Il prodotto costa troppo.',3,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-15',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',4,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-02',1,'Il prodotto non funziona.',5,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',6,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-02',2,'Il prodotto costa troppo.',7,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-17',2,'Il prodotto costa troppo.',8,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-22',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',9,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-18',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',10,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-18',2,'Il prodotto costa troppo.',12,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-22',2,'Il prodotto costa troppo.',13,100);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-08',2,'Il prodotto costa troppo.',14,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-26',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',15,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-07',2,'Il prodotto costa troppo.',16,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-14',2,'Il prodotto costa troppo.',17,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-03',2,'Il prodotto costa troppo.',18,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-09',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',19,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-05',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',20,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-02',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',21,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-13',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',22,101);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-08',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',23,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-21',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',24,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-01',1,'Il prodotto non funziona.',25,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',26,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-20',2,'Il prodotto costa troppo.',27,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-21',1,'Il prodotto non funziona.',28,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-13',2,'Il prodotto costa troppo.',29,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-11',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',30,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-02',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',31,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-15',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',32,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-08',1,'Il prodotto non funziona.',33,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-08',2,'Il prodotto costa troppo.',34,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-04',2,'Il prodotto costa troppo.',35,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-06',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',36,102);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-05',2,'Il prodotto costa troppo.',37,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-04',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',38,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-01',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',39,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-17',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',40,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',41,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-07',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',42,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-31',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',43,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-31',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',44,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-30',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',45,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-29',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',46,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-12',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',47,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-01',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',48,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-09',2,'Il prodotto costa troppo.',2,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-20',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',3,103);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-21',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',4,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-23',2,'Il prodotto costa troppo.',5,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-22',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',6,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-12',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',7,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-18',1,'Il prodotto non funziona.',8,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-20',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',9,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-10',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',10,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',11,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-29',1,'Il prodotto non funziona.',12,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-21',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',13,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-14',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',14,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-23',1,'Il prodotto non funziona.',15,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-04',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',16,104);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-27',2,'Il prodotto costa troppo.',17,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-24',1,'Il prodotto non funziona.',18,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-16',1,'Il prodotto non funziona.',19,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-22',2,'Il prodotto costa troppo.',20,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',21,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',22,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-17',2,'Il prodotto costa troppo.',23,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-01',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',24,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-19',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',25,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-27',2,'Il prodotto costa troppo.',26,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-15',1,'Il prodotto non funziona.',27,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-11',1,'Il prodotto non funziona.',28,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-24',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',29,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-04',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',30,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',31,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-23',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',32,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-17',1,'Il prodotto non funziona.',33,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-24',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',34,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',35,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',36,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-05',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',37,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-19',2,'Il prodotto costa troppo.',38,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-27',2,'Il prodotto costa troppo.',39,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-06',2,'Il prodotto costa troppo.',40,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-30',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',41,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',42,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-05',2,'Il prodotto costa troppo.',43,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-15',2,'Il prodotto costa troppo.',44,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-21',1,'Il prodotto non funziona.',45,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-29',2,'Il prodotto costa troppo.',46,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-13',2,'Il prodotto costa troppo.',47,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-19',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',48,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-02',1,'Il prodotto non funziona.',2,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-29',1,'Il prodotto non funziona.',3,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-04',1,'Il prodotto non funziona.',4,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-05',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',5,105);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-09-05',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',6,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-08',1,'Il prodotto non funziona.',7,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-29',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',8,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',9,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-03',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',10,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-02-26',1,'Il prodotto non funziona.',11,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-16',1,'Il prodotto non funziona.',12,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-18',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',13,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-01',2,'Il prodotto costa troppo.',14,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-02-16',1,'Il prodotto non funziona.',15,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-28',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',16,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-03-08',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',17,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-11',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',18,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-13',1,'Il prodotto non funziona.',19,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-20',2,'Il prodotto costa troppo.',20,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-03-21',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',21,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-30',2,'Il prodotto costa troppo.',22,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-05-22',2,'Il prodotto costa troppo.',23,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-28',1,'Il prodotto non funziona.',24,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-07',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',25,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-04',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',26,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',27,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-14',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',28,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-03',2,'Il prodotto costa troppo.',29,106);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-07-09',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',30,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-12',1,'Il prodotto non funziona.',31,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-01-18',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',32,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-23',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',33,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-28',2,'Il prodotto costa troppo.',34,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-11',1,'Il prodotto non funziona.',35,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-11',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',36,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-12-16',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',37,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-01-25',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',38,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-06-26',3,'Il prodotto è di scarsa qualità, tuttavia funziona correttamente.',39,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-10-07',4,'Il prodotto ha un ottimo rapporto qualità prezzo.',40,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-05-26',2,'Il prodotto costa troppo.',41,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-08-15',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',42,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-11-15',2,'Il prodotto costa troppo.',43,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-29',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',44,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-07-04',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',45,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2017-04-06',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',46,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-06-26',2,'Il prodotto costa troppo.',47,107);
INSERT INTO ProductReview(CreationDate,Rating,Description,ProductID,UserID) VALUES ('2016-04-13',5,'Il prodotto è di ottima qualità, ne consiglio l''acquisto.',48,107);
