INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (1,200,'2017-03-27',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (2,1,'2016-08-17',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (3,2,'2016-09-04',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (4,3,'2017-07-25',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (5,4,'2016-01-06',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (6,5,'2017-06-26',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (7,6,'2016-11-05',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (8,7,'2016-08-13',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (9,8,'2016-02-19',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (10,9,'2016-08-29',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (11,10,'2016-09-27',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (12,11,'2017-02-23',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (13,12,'2017-02-23',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (14,13,'2017-02-26',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (15,14,'2016-11-04',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (16,15,'2016-07-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (17,16,'2016-03-27',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (18,17,'2016-09-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (19,18,'2016-09-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (20,19,'2017-05-01',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (21,20,'2017-07-28',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (22,21,'2016-05-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (23,22,'2016-03-08',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (24,23,'2016-10-02',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (25,24,'2017-04-26',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (26,25,'2016-11-10',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (27,26,'2016-10-06',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (28,27,'2016-08-30',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (29,28,'2017-06-29',1,'Esperienza negativa. Negozio sconsigliato.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (30,29,'2016-06-18',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (31,30,'2017-04-14',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (32,31,'2016-07-05',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (33,32,'2016-03-30',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (34,33,'2016-04-22',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (35,34,'2016-10-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (36,35,'2017-05-20',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (37,36,'2017-05-12',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (38,37,'2016-09-19',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (39,38,'2016-09-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (40,39,'2017-02-01',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (41,40,'2017-02-18',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (42,41,'2017-03-31',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (43,42,'2016-02-04',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (44,43,'2016-01-05',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (45,44,'2016-09-10',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (46,45,'2016-01-22',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (47,46,'2017-01-03',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (48,47,'2016-08-24',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (49,48,'2016-04-07',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (50,49,'2016-08-16',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (51,50,'2017-03-29',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (52,51,'2016-05-04',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (53,52,'2017-01-28',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (54,53,'2017-07-05',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (55,54,'2016-02-25',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (56,55,'2016-10-17',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (57,56,'2017-03-13',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (58,57,'2016-11-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (59,58,'2016-04-02',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (60,59,'2016-07-13',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (61,60,'2017-06-16',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (62,61,'2016-03-16',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (63,62,'2017-01-08',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (64,63,'2016-10-09',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (65,64,'2017-05-19',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (66,65,'2016-07-20',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (67,66,'2016-10-21',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (68,67,'2016-02-27',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (69,68,'2017-04-10',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (70,69,'2017-05-22',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (71,70,'2016-04-04',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (72,71,'2016-11-03',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (73,72,'2017-05-27',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (74,73,'2016-12-31',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (75,74,'2017-06-08',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (76,75,'2016-07-22',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (77,76,'2017-01-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (78,77,'2016-06-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (79,78,'2016-07-20',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (80,79,'2017-06-15',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (81,80,'2017-04-30',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (82,81,'2017-07-11',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (83,82,'2016-04-23',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (84,83,'2016-10-31',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (85,84,'2016-02-04',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (86,85,'2017-02-13',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (87,86,'2017-05-06',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (88,87,'2017-06-10',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (89,88,'2017-05-31',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (90,89,'2017-06-22',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (91,90,'2016-04-14',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (92,91,'2016-03-29',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (93,92,'2016-11-16',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (94,93,'2017-07-11',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (95,94,'2016-02-02',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (96,95,'2017-05-01',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (97,96,'2016-07-05',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (98,97,'2016-08-25',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (99,98,'2017-02-03',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (100,99,'2016-10-03',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (101,100,'2016-10-05',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (102,101,'2017-04-23',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (103,102,'2016-07-25',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (104,103,'2016-05-27',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (105,104,'2017-07-13',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (106,105,'2017-02-08',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (107,106,'2016-01-25',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (108,107,'2016-09-07',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (109,108,'2017-07-11',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (110,109,'2017-05-09',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (111,110,'2017-03-18',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (112,111,'2016-11-23',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (113,112,'2016-09-18',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (114,113,'2016-11-02',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (115,114,'2016-10-11',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (116,115,'2016-05-31',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (117,116,'2016-08-30',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (118,117,'2016-03-09',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (119,118,'2017-01-15',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (120,119,'2017-07-26',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (121,120,'2016-12-06',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (122,121,'2016-03-24',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (123,122,'2016-07-05',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (124,123,'2017-05-06',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (125,124,'2017-04-01',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (126,125,'2017-03-03',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (127,126,'2016-08-14',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (128,127,'2016-06-04',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (129,128,'2017-05-06',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (130,129,'2017-04-29',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (131,130,'2017-02-24',1,'Esperienza negativa. Negozio sconsigliato.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (132,131,'2016-10-10',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (133,132,'2016-02-04',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (134,133,'2016-08-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (135,134,'2017-01-14',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (136,135,'2016-02-14',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (137,136,'2016-06-16',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (138,137,'2017-03-14',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (139,138,'2016-08-15',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (140,139,'2017-07-29',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (141,140,'2016-11-14',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (142,141,'2016-02-17',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (143,142,'2016-06-13',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (144,143,'2017-07-18',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (145,144,'2017-06-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (146,145,'2016-07-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (147,146,'2016-06-01',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (148,147,'2016-11-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (149,148,'2017-01-31',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (150,149,'2017-01-18',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (151,150,'2017-03-09',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (152,151,'2017-04-04',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (153,152,'2016-09-16',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (154,153,'2016-02-23',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (155,154,'2016-02-08',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (156,155,'2017-05-18',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (157,156,'2016-02-18',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (158,157,'2016-07-28',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (159,158,'2016-06-10',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (160,159,'2017-02-15',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (161,160,'2016-10-24',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (162,161,'2016-07-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (163,162,'2016-05-28',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (164,163,'2016-03-08',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (165,164,'2016-11-12',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (166,165,'2016-05-09',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (167,166,'2017-07-02',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (168,167,'2016-05-11',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (169,168,'2016-04-01',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (170,169,'2016-12-06',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (171,170,'2016-01-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (172,171,'2016-05-28',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (173,172,'2016-08-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (174,173,'2016-12-08',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (175,174,'2017-06-01',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (176,175,'2016-07-20',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (177,176,'2017-06-16',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (178,177,'2017-06-02',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (179,178,'2016-08-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (180,179,'2017-01-14',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (181,180,'2017-05-08',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (182,181,'2016-04-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (183,182,'2016-07-17',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (184,183,'2017-01-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (185,184,'2016-12-12',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (186,185,'2016-10-07',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (187,186,'2017-04-14',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (188,187,'2016-07-28',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (189,188,'2016-05-11',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (190,189,'2017-01-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (191,190,'2016-07-21',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (192,191,'2016-07-16',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (193,192,'2016-06-05',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (194,193,'2016-07-14',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (195,194,'2016-04-30',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (196,195,'2016-04-22',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (197,196,'2016-10-21',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (198,197,'2016-06-22',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (199,198,'2017-02-20',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (200,199,'2017-02-12',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (201,1,'2016-09-12',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (202,2,'2016-04-18',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (203,3,'2016-11-24',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (204,4,'2017-02-14',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (205,5,'2017-06-24',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (206,6,'2016-08-20',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (207,7,'2017-03-28',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (208,8,'2016-12-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (209,9,'2017-07-13',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (210,10,'2016-01-07',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (211,11,'2017-06-10',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (212,12,'2016-06-23',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (213,13,'2017-01-09',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (214,14,'2016-12-22',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (215,15,'2016-06-22',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (216,16,'2016-06-26',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (217,17,'2016-09-11',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (218,18,'2016-07-22',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (219,19,'2016-02-24',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (220,20,'2016-09-25',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (221,21,'2017-03-24',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (170,17,'2016-08-03',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (171,18,'2016-11-22',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (172,19,'2017-05-24',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (173,20,'2016-06-05',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (174,21,'2017-06-01',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (175,22,'2017-05-17',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (176,23,'2017-03-30',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (177,24,'2017-05-08',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (178,25,'2016-10-03',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (179,26,'2016-01-17',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (180,27,'2016-09-20',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (181,28,'2017-03-19',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (182,29,'2017-07-31',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (183,30,'2016-08-09',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (184,31,'2016-12-15',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (185,32,'2017-03-16',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (186,33,'2017-07-19',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (187,34,'2016-05-21',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (188,35,'2017-03-10',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (189,36,'2016-01-11',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (190,37,'2016-03-24',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (191,38,'2017-07-20',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (192,39,'2016-09-23',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (193,40,'2016-04-26',3,'Il prodotto non arrivava ma il supporto è stato molto utile e disponibile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (194,41,'2016-06-26',2,'Il prodotto è arrivato in ritardo.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (195,42,'2017-05-14',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (196,43,'2017-07-17',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (197,44,'2017-03-22',1,'Esperienza negativa. Negozio sconsigliato.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (198,45,'2016-08-03',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (199,46,'2016-08-05',4,'Il prodotto è arrivato nei tempi prestabiliti, personale disponibile e gentile.');
INSERT INTO ShopReview(UserID,ShopID,CreationDate,Rating,Description) VALUES (200,47,'2016-05-04',5,'Prezzi bassi e qualità del servizio eccellente, consiglio l''acquisto da questo negozio.');
